package com.example.csci3310_airdrop_proj.service;

import android.app.Notification;
import android.app.NotificationChannel;
import android.app.NotificationManager;
import android.content.Intent;
import android.content.pm.ServiceInfo;
import android.net.Uri;
import android.os.Build;
import android.util.Log;

import androidx.core.app.NotificationCompat;
import androidx.lifecycle.LifecycleService;

import com.example.csci3310_airdrop_proj.model.SharedFile;
import com.example.csci3310_airdrop_proj.repository.FirebaseSharedDriveRepository;
import com.example.csci3310_airdrop_proj.repository.SharedDriveRepository;

import java.util.concurrent.atomic.AtomicInteger;

/**
 * Foreground Service that uploads a file to the Firebase-backed Shared Drive.
 *
 * Started by {@code MainActivity.uploadFile()} after the user taps Upload in
 * {@code SendModeFragment}. The user can then navigate anywhere — the
 * Firestore snapshot listener in {@code FileListFragment} will pick up the
 * uploaded document automatically whenever the user returns to the Drive tab.
 *
 * Uses the same foreground-service pattern as {@link FileTransferService}:
 *  - Calls {@code startForeground()} immediately (within 5 s, required on API 34+)
 *  - Declares {@code foregroundServiceType="dataSync"} in the manifest
 *  - Shows a progress notification with a determinate progress bar
 *
 * Concurrency: each Intent delivered via {@code onStartCommand} starts a new
 * upload. An in-flight counter keeps the service alive until every concurrent
 * upload finishes. The foreground notification reflects the most recent
 * upload's progress; per-completion/failure notifications use unique IDs so
 * they persist in the tray.
 */
public class FileUploadService extends LifecycleService {

    private static final String TAG        = "FileUploadService";
    private static final String CHANNEL_ID = "dropdroid_upload";
    private static final int    FG_NOTIF_ID = 2001;

    public static final String EXTRA_URI        = "extra_uri";
    public static final String EXTRA_FILE_NAME  = "extra_file_name";
    public static final String EXTRA_MIME_TYPE  = "extra_mime_type";
    public static final String EXTRA_FILE_SIZE  = "extra_file_size";
    /** Id generated by {@link UploadQueue#enqueue} — lets the service update the right row. */
    public static final String EXTRA_QUEUE_ID   = "extra_queue_id";

    private final AtomicInteger inflight = new AtomicInteger(0);
    private final AtomicInteger nextCompletionNotifId = new AtomicInteger(3000);

    private SharedDriveRepository repository;
    private NotificationManager   notifManager;
    private UploadQueue           queue;

    // ── Lifecycle ────────────────────────────────────────────────────────────

    @Override
    public void onCreate() {
        super.onCreate();
        repository   = new FirebaseSharedDriveRepository();
        notifManager = (NotificationManager) getSystemService(NOTIFICATION_SERVICE);
        queue        = UploadQueue.get();
        createNotificationChannel();
    }

    @Override
    public int onStartCommand(Intent intent, int flags, int startId) {
        super.onStartCommand(intent, flags, startId);

        // Must go foreground before we do anything else.
        startInForeground(null, 0);

        if (intent == null) {
            maybeStopIfIdle();
            return START_NOT_STICKY;
        }

        Uri    uri      = intent.getParcelableExtra(EXTRA_URI);
        String fileName = intent.getStringExtra(EXTRA_FILE_NAME);
        String mimeType = intent.getStringExtra(EXTRA_MIME_TYPE);
        long   fileSize = intent.getLongExtra(EXTRA_FILE_SIZE, 0);
        String queueId  = intent.getStringExtra(EXTRA_QUEUE_ID);

        if (uri == null || fileName == null) {
            Log.e(TAG, "Missing URI or fileName — dropping");
            maybeStopIfIdle();
            return START_NOT_STICKY;
        }

        // If the caller didn't pre-register in the queue, do it now so the
        // pending row still appears (e.g. if the service is started directly).
        final String id = (queueId != null)
                ? queueId
                : queue.enqueue(fileName, mimeType, fileSize);

        inflight.incrementAndGet();
        updateForeground(fileName, 0);

        repository.uploadFile(uri, fileName, mimeType, fileSize, getContentResolver(),
                new SharedDriveRepository.UploadCallback() {
                    @Override public void onProgress(int percent) {
                        queue.updateProgress(id, percent);
                        updateForeground(fileName, percent);
                    }
                    @Override public void onSuccess(SharedFile file) {
                        queue.markSuccess(id);
                        showCompletionNotification(file.getFileName(), true, null);
                        onUploadDone();
                    }
                    @Override public void onFailure(Exception e) {
                        String msg = e.getMessage() != null ? e.getMessage() : "unknown";
                        Log.e(TAG, "Upload failed: " + fileName, e);
                        queue.markFailure(id, msg);
                        showCompletionNotification(fileName, false, msg);
                        onUploadDone();
                    }
                });

        return START_NOT_STICKY;
    }

    private void onUploadDone() {
        inflight.decrementAndGet();
        maybeStopIfIdle();
    }

    private void maybeStopIfIdle() {
        if (inflight.get() <= 0) {
            stopForeground(STOP_FOREGROUND_DETACH); // keep the latest notification visible
            stopSelf();
        }
    }

    // ── Notifications ────────────────────────────────────────────────────────

    private void createNotificationChannel() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            NotificationChannel channel = new NotificationChannel(
                    CHANNEL_ID,
                    "DroidDrop Uploads",
                    NotificationManager.IMPORTANCE_LOW);
            channel.setDescription("Background uploads to the Shared Drive");
            channel.setShowBadge(false);
            notifManager.createNotificationChannel(channel);
        }
    }

    private void startInForeground(String fileName, int percent) {
        Notification notif = buildProgressNotification(fileName, percent);
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.UPSIDE_DOWN_CAKE) {
            startForeground(FG_NOTIF_ID, notif, ServiceInfo.FOREGROUND_SERVICE_TYPE_DATA_SYNC);
        } else {
            startForeground(FG_NOTIF_ID, notif);
        }
    }

    private void updateForeground(String fileName, int percent) {
        notifManager.notify(FG_NOTIF_ID, buildProgressNotification(fileName, percent));
    }

    private Notification buildProgressNotification(String fileName, int percent) {
        String title = fileName != null ? ("Uploading " + fileName) : "Uploading";
        String text  = percent + "%";
        return new NotificationCompat.Builder(this, CHANNEL_ID)
                .setContentTitle(title)
                .setContentText(text)
                .setSmallIcon(android.R.drawable.stat_sys_upload)
                .setProgress(100, percent, /*indeterminate=*/ fileName == null)
                .setOngoing(true)
                .setOnlyAlertOnce(true)
                .setPriority(NotificationCompat.PRIORITY_LOW)
                .build();
    }

    private void showCompletionNotification(String fileName, boolean success, String errorOrNull) {
        int id = nextCompletionNotifId.incrementAndGet();
        String title = success ? "Uploaded" : "Upload failed";
        String text  = success
                ? fileName + " added to the Shared Drive"
                : fileName + (errorOrNull != null ? " — " + errorOrNull : "");
        int icon = success
                ? android.R.drawable.stat_sys_upload_done
                : android.R.drawable.stat_notify_error;
        Notification notif = new NotificationCompat.Builder(this, CHANNEL_ID)
                .setContentTitle(title)
                .setContentText(text)
                .setSmallIcon(icon)
                .setAutoCancel(true)
                .setPriority(NotificationCompat.PRIORITY_DEFAULT)
                .build();
        notifManager.notify(id, notif);
    }
}
